name: Check Licenses
on:
  push:
    branches: [master, preprod, OS-1]
  pull_request:

jobs:
  lint:
    name: Check licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile

      - name: Check licenses
        uses: packpacka/nodejs-license-checker@v0.1.6
        with:
          allow-only: 'MIT;BSD;BSD-3-Clause;BSD-2-Clause;0BSD;WTFPL;Apache*;Apache-2.0;Apache License;ISC;ะกะก0;CC0-1.0;CC-BY-3.0;CC-BY-4.0;X11;The Artistic License 2.0;CC0-1.0;Mozilla Public License 2.0;Boost Software License 1.0;Unlicense;(MIT OR CC0-1.0);(MIT OR Apache-2.0);(MIT AND BSD-3-Clause)'
          exclude-packages: 'amdefine@1.0.1;asn1@0.1.11;assert-plus@0.1.5;colors@0.5.1;combined-stream@0.0.7;ctype@0.5.3;delayed-stream@0.0.5;duplexer2@0.0.2;form-data@0.0.8;format-package-json@0.2.0;github@0.1.16;indexof@0.0.1;is@0.2.7;json-stringify-safe@4.0.0;locale@0.1.0;mime@1.2.11;nomnom@1.6.2;optimist@0.6.1;qs@0.6.6;rx-lite-aggregates@4.0.8;rx-lite@4.0.8;spdx-ranges@2.1.1;underscore@1.4.4;weak-map@1.0.5;json-schema@0.2.3;path-is-inside@1.0.2;wordwrap@0.0.2'



