name: Check Licenses
on:
  push:
    branches: [master, preprod, OS-1]
  pull_request:

jobs:
  lint:
    name: Check licenses
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: yarn install --frozen-lockfile

      - name: Check licenses
        uses: packpacka/nodejs-license-checker@v0.1.6
        with:
          allow-only: 'MIT;BSD'
          exclude-packages: 'abbrev@1.0.9;abbrev@1.1.1;amdefine@1.0.1;asn1@0.1.11;assert-plus@0.1.5;atob@2.1.1;atob@2.1.2;aws-sign2@0.7.0;aws-sign@0.3.0;bcrypt-pbkdf@1.0.2;browser-stdout@1.3.0;caseless@0.12.0;cli-width@2.2.1;cliui@2.1.0;cliui@4.1.0;colors@0.5.1;combined-stream@0.0.7;cookie-jar@0.3.0;ctype@0.5.3;delayed-stream@0.0.5;detectionizr@0.1.5;dezalgo@1.0.3;diff@3.3.1;doctrine@2.1.0;duplexer2@0.0.2;escodegen@1.8.1;eslint-scope@3.7.3;eslint-visitor-keys@1.3.0;espree@3.5.4;esprima@2.7.3;esprima@4.0.1;esquery@1.4.0;esrecurse@4.3.0;estraverse@4.3.0;estraverse@5.2.0;esutils@2.0.3;foreground-child@1.5.6;forever-agent@0.5.2;forever-agent@0.6.1;form-data@0.0.8;format-package-json@0.2.0;fs.realpath@1.0.0;get-caller-file@1.0.2;get-caller-file@1.0.3;once@1.4.0;optimist@0.6.1;osenv@0.1.5;path-is-inside@1.0.2;pseudomap@1.0.2;qs@0.6.6;qs@6.5.2;read-installed@4.0.3;read-package-json@2.1.2;read@1.0.7;readdir-scoped-modules@1.1.0;remove-trailing-separator@1.1.0;request@2.22.0;request@2.88.2;require-main-filename@1.0.1;rimraf@2.6.2;rimraf@2.6.3;rimraf@2.7.1;rx-lite-aggregates@4.0.8;rx-lite@4.0.8;semver@5.4.1;semver@5.5.0;semver@5.7.1;set-blocking@2.0.0;shelljs@0.7.8;signal-exit@3.0.2;signal-exit@3.0.3;slide@1.1.6;source-map@0.4.4;source-map@0.5.7;source-map@0.6.1;spawn-wrap@1.4.2;spawn-wrap@1.4.3;spdx-correct@3.0.0;spdx-correct@3.1.1;spdx-exceptions@2.1.0;spdx-exceptions@2.3.0;spdx-license-ids@3.0.0;spdx-license-ids@3.0.7;spdx-ranges@2.1.1;sprintf-js@1.0.3;table@4.0.2;test-exclude@4.2.1;test-exclude@4.2.3;tough-cookie@2.5.0;tunnel-agent@0.3.0;tunnel-agent@0.6.0;tweetnacl@0.14.5;uglify-js@2.8.29;uglify-js@3.13.5;underscore@1.4.4;uri-js@4.4.1;validate-npm-package-license@3.0.3;validate-npm-package-license@3.0.4;weak-map@1.0.5;which-module@2.0.0;which@1.3.0;which@1.3.1;wordwrap@0.0.2;wrappy@1.0.2;write-file-atomic@1.3.4;y18n@3.2.1;y18n@3.2.2;yallist@2.1.2;yargs-parser@8.1.0;yargs-parser@9.0.2'



